services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=messanger_db
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - ./app/.env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/messanger_db
    command: >
      sh -c "until alembic upgrade head; do
        echo '⏳Ждем запуска БД...';
        sleep 2;
      done && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
volumes:
  postgres_data:
    driver: local